// index
export const CLEAR_STATE = 'CLEAR_STATE';

// display value
export const CHANGE_DISPLAY_VALUE = 'CHANGE_DISPLAY_VALUE';
export const CHANGE_VALUE = 'CHANGE_VALUE';
export const DELETE_LAST_DIGIT = 'DELETE_LAST_DIGIT';
export const CLEAR_DISPLAY_VALUE = 'CLEAR_DISPLAY_VALUE';
export const CHANGE_SIGN = 'CHANGE_SIGN';
export const ADD_DOT = 'ADD_DOT';

// operations
export const DO_OPERATION = 'DO_OPERATION';
export const DO_SINGLE_OPERATION = 'DO_SINGLE_OPERATION';
export const SET_OPERATION  = 'SET_OPERATION';

// waiting second operand
export const ON_WAITING_SECOND_NUMBER = 'ON_WAITING_SECOND_NUMBER';
export const OFF_WAITING_SECOND_NUMBER = 'OFF_WAITING_SECOND_NUMBER';

// History items
export const ADD_HISTORY_ITEM = 'ADD_HISTORY_ITEM';
export const UPDATE_OPERATION = 'UPDATE_OPERATION';
export const CLEAR_OPERATION = 'CLEAR_OPERATION';

// Memory value
export const MEMORY_CHANGE = 'MEMORY_CHANGE';
export const MEMORY_PLUS = 'MEMORY_PLUS';
export const MEMORY_MINUS = 'MEMORY_MINUS';
export const MEMORY_CLEAR = 'MEMORY_CLEAR';

// Operations
export const CHANGE_CURRENT_OPERATION = 'CHANGE_CURRENT_OPERATION';
export const CONVERT_OPERATION = 'CONVERT_OPERATION';
export const SET_CURRENT_OPERATION = 'SET_CURRENT_OPERATION';

// ResultIsReady
export const TOGGLE_READY_RESULT = 'TOGGLE_READY_RESULT';
